// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
//  import "./globals.css";
// import { ThemeProvider } from "@/components/them-provider";
 import { Sidebar } from "@/components/sidebar";
 import  {Navbar}  from "@/components/header";
 import { Providers } from "@/components/providers/session-provider";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >

//       <body className="overflow-hidden">
//         <ThemeProvider
//         attribute="class"
//         defaultTheme="dark"
//         enableSystem
//         disableTransitionOnChange>
//           <div className="flex h-screen overflow-hidden bg-background">
//             <Sidebar/>
//             <div className="flex-1 flex flex-col overflow-hidden">
//               <Navbar/>
//               <main className="flex-1 overflow-y-auto p-8 custom-scrollbar">
//                 <Providers>
//                   {children}
//                 </Providers>

//               </main>

//             </div>

//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
import { auth } from "@/auth";
import { Toaster } from "sonner";
import {Nav} from "@/components/layout/Navbar";
import { BootSequence } from "@/components/layout/boot-sequence";
const  DashboardLayout  = ({ children }: { children: React.ReactNode }) => {
    
    
  return (
    
    
      <section className="h-full relative bg-[#020205] text-white">
        <Toaster
        theme="dark"
        position="bottom-right"
        toastOptions={{
          style:{
            background:"#080810",
            border:"1px solid rgba(255,255,255,0.05)",
            color:"#fff",
            
          }
        }}/>

      
      <div className="hidden h-full md:flex md:w-72 md:flex-col md:fixed md:inset-y-0 z-50">
        <Sidebar />
      </div>

    
      <main className="md:pl-72 flex flex-col h-full">
 
        <Nav/>
        
       
        <div className="flex-1 overflow-y-auto relative p-8 h-full">
           
            <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-purple-600/5 blur-[120px] -z-10" />
           <BootSequence> {children}</BootSequence>
        </div>
      </main>
    </section>
    
  );
};

export default DashboardLayout;